// Builds dist/room-climate-card.js: one dependency-free, non-minified IIFE, plugin-free.
// Full contract: see internal dev doc §4 "Build-/Dist-Vertrag" and §5 "Build, Rollup und
// HACS-Artefakt". The output is deterministic per source state and Rollup version but not
// a literal concatenation of the sources. Line endings are pinned to LF (.gitattributes).

export default {
  input: "src/index.js",
  output: {
    file: "dist/room-climate-card.js",
    format: "iife",
    // The IIFE needs an explicit strict-mode prologue; source-module strictness alone
    // does not state that contract in the generated bundle.
    strict: true,
    // No source map in the product build: HACS serves only .js, so a .map would 404. Coverage
    // builds opt into an inline map through a test-owned env flag.
    sourcemap: process.env.ROOM_CLIMATE_CARD_COVERAGE === "1" ? "inline" : false,
    // Keeps the src/ indentation instead of adding a level for the IIFE wrapper (readability).
    indent: false,
    banner:
      "/* Room Climate Card — generated by `npm run build` from src/. Do not edit.\n" +
      "   Source, tests and documentation: https://github.com/hyperfelixations/room-climate-card */",
  },
  // Off for correctness, not size: Rollup's DCE also rewrites object literals and drops
  // module-load side effects (key-parity self-check, derived unit index, registration) that
  // are load-bearing. Dead code is deleted in src/, where it is reviewable.
  treeshake: false,
  // Every import must resolve locally; an unresolved specifier or a circular import fails
  // the build rather than degrading the artifact.
  onwarn(warning) {
    throw new Error(`Rollup warning treated as an error (${warning.code}): ${warning.message}`);
  },
};
