// Build for the Home Assistant / HACS distribution artifact.
//
// Contract: src/ is ES-module source, dist/room-climate-card.js is ONE
// dependency-free, non-minified IIFE. Home Assistant loads that file directly
// as a dashboard resource, and HACS serves it verbatim from dist/ — there is
// no install step on the user's side, so the artifact must stay self-contained
// and readable.
//
// Deliberately plugin-free. The card has no dependencies, no JSX, no
// TypeScript and targets the same modern browsers Home Assistant's own
// frontend requires, so there is nothing to resolve, transpile or inject.
// Every plugin added here would be a new supply-chain dependency for a file
// that thousands of dashboards execute.
//
// Rollup preserves source comments in the bundle. Those comments document
// public contracts and non-obvious invariants for anyone inspecting the HACS
// artifact; AST reprinting tools may drop them.
//
// What the build does and does not guarantee:
//   - Rollup parses and bundles ES modules. Import/export statements are
//     removed, and top-level declarations may be reordered or renamed where
//     names collide between modules.
//   - `treeshake: false` (below) disables dead-code elimination. It does NOT
//     disable every other transformation, and the output is therefore not a
//     literal concatenation of the source files.
//   - What IS guaranteed: the bundle is deterministic for a given source state
//     and Rollup version, unminified and readable, self-contained, free of
//     runtime dependencies, and verified behaviourally by the full test suite
//     plus the characterization baselines and golden screenshots.
//   - Rollup can carry line endings from source segments into the output, so
//     sources and artifact are both pinned to LF (see .gitattributes).

export default {
  input: "src/index.js",
  output: {
    file: "dist/room-climate-card.js",
    format: "iife",
    // The IIFE needs an explicit strict-mode prologue; source-module strictness alone
    // does not state that contract in the generated bundle.
    strict: true,
    // No source map in the product build: HACS downloads only .js files from dist/, so a .map would
    // never reach the browser and its sourceMappingURL would 404 on every
    // dashboard load. The unminified bundle is its own debugging aid.
    // Coverage builds opt into an inline map; the environment flag is owned by test tooling
    // and never used by the release workflow.
    sourcemap: process.env.ROOM_CLIMATE_CARD_COVERAGE === "1" ? "inline" : false,
    // Suppresses the extra indentation level Rollup would otherwise add for
    // the IIFE wrapper, so the bundled code keeps the indentation it has in
    // src/. That is a readability choice only — with several modules the
    // bundle is still not line-for-line equal to any source file (see the
    // header comment on what the build does and does not guarantee).
    indent: false,
    banner:
      "/* Room Climate Card — generated by `npm run build` from src/. Do not edit.\n" +
      "   Source, tests and documentation: https://github.com/hyperfelixations/room-climate-card */",
  },
  // Tree-shaking is OFF, and this is a correctness decision, not a size one.
  //
  // Rollup's dead-code elimination also rewrites object literals: with it
  // enabled it silently dropped `auto_slide` and `swipe` from DEFAULT_CONFIG,
  // because _normalizeConfig() happens to derive both from the user config
  // instead of reading the defaults back. Harmless there — but a build that
  // removes data visible in the source makes the artifact harder to
  // reason about than it needs to be. The card's module-load side effects (the
  // translation key-parity self-check, the derived unit index, the easing
  // constant, the customElements.define()/window.customCards registration)
  // are load-bearing for the same reason.
  //
  // With this off, nothing is dropped for being unreferenced; genuinely dead
  // code gets deleted in src/, where it is reviewable. It does not make the
  // bundle a literal concatenation — see the header comment.
  treeshake: false,
  // A dependency-free bundle must resolve every import locally. Anything
  // Rollup cannot resolve, or any circular import introduced by a later
  // extraction step, has to fail the build rather than degrade the artifact.
  onwarn(warning) {
    throw new Error(`Rollup warning treated as an error (${warning.code}): ${warning.message}`);
  },
};
