// Builds dist/room-climate-card-dev.js: the card under a development identity, loadable as a
// second dashboard resource beside the released card without either replacing the other.
// Only src/core/card-metadata.js is swapped; everything else is the product build from
// rollup.config.mjs. See internal dev doc §4 "Build-/Dist-Vertrag".

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { rollup } from "rollup";
import productConfig from "../rollup.config.mjs";

const MODULE_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(MODULE_PATH), "..");
const METADATA_PATH = path.join(ROOT, "src", "core", "card-metadata.js");
const REPOSITORY_URL = "https://github.com/hyperfelixations/room-climate-card";

export const DEV_OUTPUT = path.join(ROOT, "dist", "room-climate-card-dev.js");

// room-climate-card -> roomClimateCardVersion. The product global follows the same rule, which
// deriveDevIdentity() asserts, so the dev global cannot collide with it.
export function versionGlobalFor(cardType) {
  return `${cardType.replace(/-([a-z0-9])/g, (_, letter) => letter.toUpperCase())}Version`;
}

// UTC, second resolution, SemVer build-metadata safe: 20260912T153012Z.
export function buildStamp(date) {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}

// Every identity constant of card-metadata.js, re-derived for the dev build.
export function deriveDevIdentity(metadata, { builtAt, commit = null, dirty = false }) {
  if (versionGlobalFor(metadata.CARD_TYPE) !== metadata.CARD_VERSION_GLOBAL) {
    throw new Error(
      `card-metadata.js: CARD_VERSION_GLOBAL "${metadata.CARD_VERSION_GLOBAL}" does not follow from CARD_TYPE ` +
        `"${metadata.CARD_TYPE}" (expected "${versionGlobalFor(metadata.CARD_TYPE)}")`
    );
  }
  const cardType = `${metadata.CARD_TYPE}-dev`;
  const build = [buildStamp(builtAt), commit, commit && dirty ? "dirty" : null].filter(Boolean).join(".");
  return {
    CARD_TYPE: cardType,
    CARD_NAME: `${metadata.CARD_NAME} (Dev)`,
    CARD_VERSION: `${metadata.CARD_VERSION}-dev+${build}`,
    CARD_VERSION_GLOBAL: versionGlobalFor(cardType),
  };
}

// A new identity constant in card-metadata.js must be derived here too, or the dev build
// would silently share it with the released card.
export function assertSameExports(metadataExports, identity) {
  const actual = [...metadataExports].sort();
  const derived = Object.keys(identity).sort();
  if (actual.join() !== derived.join()) {
    throw new Error(
      `card-metadata.js exports ${actual.join(", ")}, but the dev build derives ${derived.join(", ")} — ` +
        "extend deriveDevIdentity() in scripts/build-dev.mjs"
    );
  }
}

export function devMetadataSource(identity) {
  const lines = Object.entries(identity).map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};`);
  return `// Development identity from scripts/build-dev.mjs; replaces src/core/card-metadata.js in this build only.\n${lines.join("\n")}\n`;
}

// Short commit id and whether the working tree differs from it; both null/false without Git.
// An unreadable status counts as dirty rather than as clean.
export function readGitInfo(cwd = ROOT) {
  const git = (args) => spawnSync("git", args, { cwd, encoding: "utf8" });
  const head = git(["rev-parse", "--short", "HEAD"]);
  if (head.error || head.status !== 0) return { commit: null, dirty: false };
  const status = git(["status", "--porcelain"]);
  return { commit: head.stdout.trim(), dirty: status.status !== 0 || status.stdout.trim() !== "" };
}

function devBanner(identity, { builtAt, commit, dirty }) {
  const origin = commit ? `commit ${commit}${dirty ? " with uncommitted changes" : ""}` : "a checkout without Git";
  return [
    `/* ${identity.CARD_NAME} ${identity.CARD_VERSION} — DEVELOPMENT BUILD, not a release.`,
    `   Generated by \`npm run build:dev\` from ${origin} at ${builtAt.toISOString()}. Do not edit.`,
    `   Registers <${identity.CARD_TYPE}> beside the released card: use \`type: custom:${identity.CARD_TYPE}\`.`,
    `   Source, tests and documentation: ${REPOSITORY_URL} */`,
  ].join("\n");
}

export async function buildDevBundle({ outFile = DEV_OUTPUT, builtAt = new Date(), git = readGitInfo() } = {}) {
  const metadata = await import(pathToFileURL(METADATA_PATH).href);
  const identity = deriveDevIdentity(metadata, { builtAt, ...git });
  assertSameExports(Object.keys(metadata), identity);

  const replacement = devMetadataSource(identity);
  let replaced = false;
  const bundle = await rollup({
    input: path.resolve(ROOT, productConfig.input),
    treeshake: productConfig.treeshake,
    onwarn: productConfig.onwarn,
    plugins: [
      {
        name: "room-climate-card-dev-identity",
        load(id) {
          if (path.relative(METADATA_PATH, id) !== "") return null;
          replaced = true;
          return replacement;
        },
      },
    ],
  });
  try {
    if (!replaced) throw new Error(`${path.relative(ROOT, METADATA_PATH)} is not part of the bundle graph`);
    await bundle.write({
      ...productConfig.output,
      file: outFile,
      // Fixed, whatever the coverage flag says: this file is uploaded, never mapped back to src/.
      sourcemap: false,
      banner: devBanner(identity, { builtAt, ...git }),
      outro: `console.info(${JSON.stringify(`${identity.CARD_NAME} ${identity.CARD_VERSION}`)});`,
    });
  } finally {
    await bundle.close();
  }
  return { outFile, identity, stamp: buildStamp(builtAt) };
}

async function main() {
  const { outFile, identity, stamp } = await buildDevBundle();
  const check = spawnSync(process.execPath, ["--check", outFile], { stdio: "inherit" });
  if (check.status !== 0) throw new Error(`node --check rejected ${outFile}`);
  const bytes = fs.readFileSync(outFile);
  const sha256 = crypto.createHash("sha256").update(bytes).digest("hex");
  console.log(
    [
      `Development build written to ${path.relative(ROOT, outFile).split(path.sep).join("/")} (${bytes.length} bytes, SHA-256 ${sha256})`,
      `  card type       custom:${identity.CARD_TYPE}`,
      `  card name       ${identity.CARD_NAME}`,
      `  version         ${identity.CARD_VERSION}`,
      `  version global  window.${identity.CARD_VERSION_GLOBAL}`,
      `  resource URL    /local/${path.basename(outFile)}?v=${stamp}`,
      "It runs beside the released card; it is never a release asset and never replaces dist/room-climate-card.js.",
    ].join("\n")
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === MODULE_PATH) {
  main().catch((error) => {
    console.error(`Development build failed: ${error.message}`);
    process.exitCode = 1;
  });
}
