// The composition root: it wires nothing together and computes nothing. It imports
// the finished custom element, registers it, and tells Home Assistant that it exists.
//
// Rollup bundles this into the single, dependency-free IIFE that Home Assistant loads
// (dist/room-climate-card.js). The IIFE wrapper and the "use strict" prologue are
// emitted by the build (see rollup.config.mjs), which is why this file starts directly
// with the module body.
//
// dist/room-climate-card.js is generated by `npm run build` and is not stored in the
// repository; never edit it by hand. Built from this source and published as the GitHub
// release asset, it is the only artifact HACS and Home Assistant ever load.
//
// The three global reads below are the one unavoidable exception to the platform
// contract: registering a custom element and announcing it to the dashboard's card
// picker are things a card can only do against the real global registry. Everything
// else in the tree reaches the browser through controllers/runtime/browser-platform.js.

import { CARD_NAME, CARD_TYPE, CARD_VERSION } from "./core/card-metadata.js";
import { RoomClimateCard } from "./element/room-climate-card.js";

// ==== Registration ====
// Registers the card as a custom element and with Home Assistant's card picker.
if (!customElements.get(CARD_TYPE)) {
  customElements.define(CARD_TYPE, RoomClimateCard);
}

window.customCards = window.customCards || [];
const existingCard = window.customCards.find((card) => card.type === CARD_TYPE);
const cardMetadata = {
  type: CARD_TYPE,
  name: CARD_NAME,
  preview: false,
  description: "Standalone climate card (temperature, humidity, CO2, or PM2.5) with an average value, comfort range, optional room extremes/chips, and HA actions.",
  documentationURL: "https://github.com/hyperfelixations/room-climate-card",
};

if (existingCard) {
  Object.assign(existingCard, cardMetadata);
} else {
  window.customCards.push(cardMetadata);
}

window.roomClimateCardVersion = CARD_VERSION;
