"use strict";

// Smoke test for the distribution contract.
//
// Everything else in the suite tests what the card DOES. This file tests what
// the shipped file IS, because that is what the build can silently break:
// HACS copies dist/room-climate-card.js into a Home Assistant installation
// verbatim and Lovelace executes it as a plain dashboard resource. There is no
// module resolver, no bundler and no network fetch on that path — a single
// stray `import` or a missing registration would fail at runtime in every
// user's browser, with nothing in this repository noticing.
//
// The bundle is therefore evaluated in a BARE jsdom realm here: no
// ResizeObserver, no matchMedia, no document.fonts stubs (unlike
// load-card.jsdom.js, which adds them so those code paths get coverage). If
// the artifact needs anything a plain browser does not already provide, this
// is where it shows up.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const { JSDOM } = require("jsdom");
const { CARD_SOURCE_PATH } = require("../helpers/load-card.jsdom.js");
const packageJson = require("../../package.json");

const CARD_TAG = "room-climate-card";
const source = fs.readFileSync(CARD_SOURCE_PATH, "utf8");

function evaluateInBareRealm() {
  const dom = new JSDOM("<!doctype html><html><body></body></html>", {
    url: "http://localhost/",
    runScripts: "outside-only",
  });
  dom.window.eval(source);
  return dom.window;
}

test("the artifact is a self-contained IIFE with no module syntax", () => {
  assert.match(source, /^\/\* Room Climate Card — generated by `npm run build`/, "must carry the generated-file banner");
  assert.match(source, /\(function \(\) \{\n'use strict';/, "must be an IIFE in strict mode");
  assert.match(source, /\}\)\(\);\n?$/, "must close its IIFE");
  assert.doesNotMatch(source, /^\s*import\s/m, "no import statements");
  assert.doesNotMatch(source, /^\s*export\s/m, "no export statements");
  assert.doesNotMatch(source, /\bimport\s*\(/, "no dynamic import()");
  assert.doesNotMatch(source, /\brequire\s*\(/, "no CommonJS require()");
  assert.doesNotMatch(source, /\/\/# sourceMappingURL/, "no source map reference (HACS ships only .js files)");
});

test("the artifact performs no network, storage, or dynamic code execution", () => {
  assert.doesNotMatch(source, /\bfetch\s*\(/, "no fetch()");
  assert.doesNotMatch(source, /\bXMLHttpRequest\b/, "no XMLHttpRequest");
  assert.doesNotMatch(source, /\bWebSocket\b/, "no WebSocket");
  assert.doesNotMatch(source, /\bimportScripts\s*\(/, "no importScripts()");
  assert.doesNotMatch(source, /\beval\s*\(/, "no eval()");
  assert.doesNotMatch(source, /new\s+Function\s*\(/, "no Function constructor");
  assert.doesNotMatch(source, /document\.write/, "no document.write()");
  assert.doesNotMatch(source, /\b(localStorage|sessionStorage)\b/, "no web storage");
  assert.doesNotMatch(source, /document\.cookie/, "no cookie access");
});

test("the artifact is shipped unminified and stays reviewable", () => {
  const lines = source.split("\n");
  assert.ok(lines.length > 5000, `expected a readable, unminified bundle, got ${lines.length} lines`);
  const longest = lines.reduce((max, line) => Math.max(max, line.length), 0);
  assert.ok(longest < 2000, `line length ${longest} suggests minified output`);
  assert.ok(source.includes("// ==== Registration ===="), "source comments must survive the build");
});

test("evaluating the artifact in a bare browser realm registers the custom element", () => {
  const window = evaluateInBareRealm();
  const ctor = window.customElements.get(CARD_TAG);
  assert.equal(typeof ctor, "function", "customElements.define() must have run at load time");
  assert.equal(ctor.name, "RoomClimateCard");
});

test("evaluating the artifact registers exactly one Home Assistant card-picker entry", () => {
  const window = evaluateInBareRealm();
  assert.ok(Array.isArray(window.customCards), "window.customCards must exist");
  const entries = window.customCards.filter((card) => card.type === CARD_TAG);
  assert.equal(entries.length, 1);
  assert.deepEqual(Object.keys(entries[0]).sort(), [
    "description",
    "documentationURL",
    "getEntitySuggestion",
    "name",
    "preview",
    "type",
  ]);
  assert.equal(entries[0].name, "Room Climate Card");
  assert.equal(entries[0].preview, true);
  // The registration baseline records this one as the string "[Function]", which pins
  // that SOMETHING is there but not that it is callable. The type is asserted here, and
  // what it answers two tests below.
  assert.equal(typeof entries[0].getEntitySuggestion, "function");
});

// The whole point of the suggestion hook is that it survives bundling and runs against
// the real registry, so it is exercised through the built artifact rather than through
// the module: a tree-shaken or reordered registration block would pass every unit test
// of card-suggestions.js and still leave the picker with nothing.
test("the artifact's suggestion hook answers for climate entities and declines everything else", () => {
  const window = evaluateInBareRealm();
  const entry = window.customCards.find((card) => card.type === CARD_TAG);
  const hass = {
    states: {
      "sensor.co2": { entity_id: "sensor.co2", state: "700", attributes: { device_class: "carbon_dioxide", unit_of_measurement: "ppm" } },
      "light.kitchen": { entity_id: "light.kitchen", state: "on", attributes: {} },
    },
  };
  // Compared field by field rather than with deepEqual: the returned object is built
  // inside the bare realm and carries that realm's prototype, which a strict deep-equal
  // rejects before it ever looks at the values.
  const suggestion = entry.getEntitySuggestion(hass, "sensor.co2");
  assert.equal(suggestion.config.type, `custom:${CARD_TAG}`);
  assert.equal(suggestion.config.entity, "sensor.co2");
  assert.equal(entry.getEntitySuggestion(hass, "light.kitchen"), null);
  assert.equal(entry.getEntitySuggestion(undefined, undefined), null, "the picker may call it before hass exists");
});

// The other half of the picker surface: with real candidates the start configuration
// names one of them, so the preview shows the user's own reading instead of an error.
test("the artifact's stub configuration prefers a real climate entity over the placeholder template", () => {
  const window = evaluateInBareRealm();
  const ctor = window.customElements.get(CARD_TAG);
  const hass = {
    states: {
      "sensor.hall": { entity_id: "sensor.hall", state: "21.4", attributes: { device_class: "temperature", unit_of_measurement: "°C" } },
    },
  };
  const stub = ctor.getStubConfig(hass, ["sensor.hall"], []);
  assert.equal(stub.entity, "sensor.hall");
  assert.equal(stub.rooms, undefined, "a real entity is offered on its own, without invented rooms beside it");
  assert.equal(ctor.getStubConfig().entity, "sensor.house_temperature", "with no arguments the documented template still comes back");
});

test("the artifact exposes its version global, matching package.json", () => {
  const window = evaluateInBareRealm();
  assert.equal(window.roomClimateCardVersion, packageJson.version);
  assert.ok(
    source.includes(`const CARD_VERSION = "${packageJson.version}"`),
    "CARD_VERSION in src/ and the package version must be released together"
  );
});

test("the package declares no runtime dependencies", () => {
  assert.equal(packageJson.dependencies, undefined, "the card must stay dependency-free for HACS");
});
