name: Validate

on:
  push:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
